### PR TITLE
Feature/odometer

### PR DESCRIPTION
**Pull request by wal-nadeem**

### CODE REVIEW

**Comment by imajneer** [comment]
@wal-nadeem This doesn't look like it's functional yet. Is that correct?

**Comment by jainwolverine** [comment]
Yes. It's not!

**Comment by imajneer** [comment]
@jainwolverine well that's unfortunate because he based quite a few other branches on this branch, so unless I want to go thru picking commits out of the rest of them, I have to merge this.

**Comment by jainwolverine** [comment]
Preston. I don't want the odometer. But I want the rest. Figure it out. Thnx.

**Comment by imajneer** [comment]
It's fine to be merged... Have to comment out some CSS and re-re-set the product modal to be reset, but that's all.

**Pull request merged**
